# Prometheus configuration for Meridian Ephemeris monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Meridian Ephemeris API metrics
  - job_name: 'meridian-api'
    static_configs:
      - targets: ['meridian-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s
    
  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 10s
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter (if added later)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Recording rules for commonly used queries
rule_files:
  - "recording_rules.yml"
  - "alerting_rules.yml"